mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips1of4.png 1-Larghetto-MarkPhillips1of4.png
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips2of4.png 1-Larghetto-MarkPhillips2of4.png
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips3of4.png 1-Larghetto-MarkPhillips3of4.png
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips4of4.png 1-Larghetto-MarkPhillips4of4.png
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.bak 1-Larghetto-MarkPhillips.bak
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.bak~ 1-Larghetto-MarkPhillips.bak~
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.ly~ 1-Larghetto-MarkPhillips.ly~
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.midi 1-Larghetto-MarkPhillips.midi
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.pdf 1-Larghetto-MarkPhillips.pdf
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips.wav 1-Larghetto-MarkPhillips.wav
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-with.ly 1-Larghetto-MarkPhillips-with.ly
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-with.ly~ 1-Larghetto-MarkPhillips-with.ly~
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-without.ly 1-Larghetto-MarkPhillips-without.ly
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-without.midi 1-Larghetto-MarkPhillips-without.midi
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-without.pdf 1-Larghetto-MarkPhillips-without.pdf
mv -v GF_Handel__Sonata_C_major__01-Larghetto-MarkPhillips-with.pdf 1-Larghetto-MarkPhillips-with.pdf
