mv -v 01-Larghetto-with.mp3 GF_Handel__Sonata_d_minor_No_2-01-Larghetto-with.mp3
mv -v 01-Larghetto-without.mp3 GF_Handel__Sonata_d_minor_No_2-01-Larghetto-without.mp3
mv -v 02-Andante-with.mp3 GF_Handel__Sonata_d_minor_No_2-02-Andante-with.mp3
mv -v 02-Andante-without.mp3 GF_Handel__Sonata_d_minor_No_2-02-Andante-without.mp3
mv -v 03-Adagio-with.mp3 GF_Handel__Sonata_d_minor_No_2-03-Adagio-with.mp3
mv -v 03-Adagio-without.mp3 GF_Handel__Sonata_d_minor_No_2-03-Adagio-without.mp3
mv -v 04-Presto-with.mp3 GF_Handel__Sonata_d_minor_No_2-04-Presto-with.mp3
mv -v 04-Presto-without.mp3 GF_Handel__Sonata_d_minor_No_2-04-Presto-without.mp3
mv -v Tune_Instrument.mp3 GF_Handel__Sonata_d_minor_No_2-Tune_Instrument.mp3
